application: thingsyoushouldread
version: 1-taskqueue
runtime: python
api_version: 1

handlers:
-   url:    /task/update/
    script: application/read.py
-   url:    /.*
    script: application/read.py

