application: thingsyoushouldread
version: 0-1
runtime: python
api_version: 1

handlers:
-   url:    /rss
    script: application/read.py
    login:  admin
-   url:    /.*
    script: application/read.py

