application: thingsyoushouldread
version: 1-alpha
runtime: python
api_version: 1

handlers:
-   url:    /task/update/
    script: application/read.py
    login:  admin
-   url:    /.*
    script: application/read.py

